# Generated by Django 5.0.4 on 2024-06-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_follow_like_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
